const ROLES = ['CITIZEN', 'RESPONDER', 'DISPATCHER', 'ADMIN'];

// Phase 3 — Citizen SOS / Disaster Report types
const REPORT_TYPES = [
    'FLOOD',
    'FIRE',
    'EARTHQUAKE',
    'LANDSLIDE',
    'CYCLONE',
    'STORM',
    'ACCIDENT',
    'BUILDING_COLLAPSE',
    'MEDICAL_EMERGENCY',
    'OTHER',
];

// Phase 3 — Report statuses (Phase 4 will extend with VERIFIED/ASSIGNED/IN_PROGRESS/RESOLVED)
const REPORT_STATUSES = ['SUBMITTED', 'RECEIVED', 'CANCELLED'];

// Phase 4+ — Incident types/statuses (kept for backward compatibility)
const INCIDENT_TYPES = REPORT_TYPES;
const INCIDENT_STATUSES = ['SUBMITTED', 'RECEIVED', 'VERIFIED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED'];

const PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];
const EVIDENCE_SOURCES = ['OFFICIAL_ALERT', 'WEATHER_DATA', 'SENSOR_DATA', 'CITIZEN_REPORT', 'RESPONDER_REPORT', 'IMAGE', 'MAP_DATA'];

module.exports = { ROLES, REPORT_TYPES, REPORT_STATUSES, INCIDENT_TYPES, INCIDENT_STATUSES, PRIORITIES, EVIDENCE_SOURCES };